### ISSUE TITLE
mob-damage flag

### ISSUE THREAD

**Issue by Grabsky** [IntellectualSites/PlotSquaredSuggestions#73] opened 2019-11-23 16:57 UTC
**PlotSquared Feature Suggestion:**
Add **mob-damage** flag whether I can toggle to let **plot owners** and **added players** take damage from mobs. Could be really useful if using PlotSquared as a SkyBlock plugin. Players that are not added to plot shouldn't be affected so they won't take damage by default.

**How should it be implemented?**
A **mob-damage** flag (boolean) possible to be set in **worlds.yml**.

**Additional context**
none

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment] 2020-04-16 15:43
And if you use the "pve" flag?

**Comment by Grabsky** [comment] 2020-04-16 18:33
I'll have to test it once more as I'm not sure. I tried several flags related to that behaviour though, no luck.

**Comment by RedstoneFuture** [comment] 2020-04-16 18:44
PVE works fine at my server and have the effect, that you described.

**Comment by Grabsky** [comment] 2020-04-16 19:18
Just tested the flag once again and it looks like mobs can hurt anyone, independent of their plot membership.

**Comment by RedstoneFuture** [comment] 2020-12-23 15:22
https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/146

**Comment by NotMyFault** [comment] 2021-02-10 15:33
Duplicate of https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/53

**Closed by NotMyFault** 2021-02-10 15:33 UTC
